# This is goreleaser configuration for releasing tcr application.
# Make sure to check the documentation at http://goreleaser.com
project_name: tcr
before:
  hooks:
    - make tidy
    - make -C webapp build
builds:
  - id: "tcr"
    dir: src
    binary: tcr
    env:
      - CGO_ENABLED=0
      - CONFIG_PKG=github.com/murex/tcr/settings
    ldflags:
      - -s -w
      - -X {{.Env.CONFIG_PKG}}.BuildVersion={{.Version}}
      - -X {{.Env.CONFIG_PKG}}.BuildOs={{.Os}}
      - -X {{.Env.CONFIG_PKG}}.BuildArch={{.Arch}}
      - -X {{.Env.CONFIG_PKG}}.BuildCommit={{.Commit}}
      - -X {{.Env.CONFIG_PKG}}.BuildDate={{.Date}}
      - -X {{.Env.CONFIG_PKG}}.BuildAuthor=murex
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{.Tag}}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
