# ----------------------------------------------------------------------------
# Example Makefile for Go language
# ----------------------------------------------------------------------------

.PHONY: build
build:
	@go test -count=0 ./...

.PHONY: test
test:
	@go test -short ./...
