graph TD
    check_config_files --> github.com/murex/tcr/checker/model
    check_config_files --> github.com/murex/tcr/config
    check_config_files --> github.com/murex/tcr/language
    check_config_files --> github.com/murex/tcr/params
    check_config_files --> github.com/murex/tcr/toolchain
    check_config_files --> path/filepath
    check_config_files_test --> github.com/murex/tcr/checker/model
    check_config_files_test --> github.com/murex/tcr/params
    check_config_files_test --> github.com/stretchr/testify/assert
    check_config_files_test --> path/filepath
    check_config_files_test --> testing
    check_directories --> github.com/murex/tcr/checker/model
    check_directories --> github.com/murex/tcr/params
    check_directories_test --> errors
    check_directories_test --> github.com/murex/tcr/checker/model
    check_directories_test --> github.com/murex/tcr/params
    check_directories_test --> github.com/stretchr/testify/assert
    check_directories_test --> io/fs
    check_directories_test --> path/filepath
    check_directories_test --> testing
    check_git --> github.com/murex/tcr/checker/model
    check_git --> github.com/murex/tcr/params
    check_git --> github.com/murex/tcr/vcs/git
    check_git --> strings
    check_git_test --> errors
    check_git_test --> github.com/murex/tcr/checker/model
    check_git_test --> github.com/murex/tcr/params
    check_git_test --> github.com/murex/tcr/vcs
    check_git_test --> github.com/murex/tcr/vcs/fake
    check_git_test --> github.com/murex/tcr/vcs/git
    check_git_test --> github.com/murex/tcr/vcs/shell
    check_git_test --> github.com/stretchr/testify/assert
    check_git_test --> testing
    check_language --> github.com/murex/tcr/checker/model
    check_language --> github.com/murex/tcr/language
    check_language --> github.com/murex/tcr/params
    check_language_test --> errors
    check_language_test --> github.com/murex/tcr/checker/model
    check_language_test --> github.com/murex/tcr/filesystem
    check_language_test --> github.com/murex/tcr/language
    check_language_test --> github.com/murex/tcr/params
    check_language_test --> github.com/stretchr/testify/assert
    check_language_test --> testing
    check_mob --> github.com/murex/tcr/checker/model
    check_mob --> github.com/murex/tcr/params
    check_mob --> time
    check_mob_test --> github.com/murex/tcr/checker/model
    check_mob_test --> github.com/murex/tcr/params
    check_mob_test --> github.com/stretchr/testify/assert
    check_mob_test --> testing
    check_mob_test --> time
    check_p4 --> github.com/murex/tcr/checker/model
    check_p4 --> github.com/murex/tcr/params
    check_p4 --> github.com/murex/tcr/utils
    check_p4 --> github.com/murex/tcr/vcs/p4
    check_p4 --> strings
    check_p4_test --> errors
    check_p4_test --> github.com/murex/tcr/checker/model
    check_p4_test --> github.com/murex/tcr/params
    check_p4_test --> github.com/murex/tcr/vcs/p4
    check_p4_test --> github.com/murex/tcr/vcs/shell
    check_p4_test --> github.com/stretchr/testify/assert
    check_p4_test --> strings
    check_p4_test --> testing
    check_toolchain --> github.com/murex/tcr/checker/model
    check_toolchain --> github.com/murex/tcr/params
    check_toolchain --> github.com/murex/tcr/toolchain
    check_toolchain --> runtime
    check_toolchain_test --> errors
    check_toolchain_test --> github.com/murex/tcr/checker/model
    check_toolchain_test --> github.com/murex/tcr/language
    check_toolchain_test --> github.com/murex/tcr/params
    check_toolchain_test --> github.com/murex/tcr/toolchain
    check_toolchain_test --> github.com/stretchr/testify/assert
    check_toolchain_test --> path/filepath
    check_toolchain_test --> runtime
    check_toolchain_test --> testing
    check_vcs --> github.com/murex/tcr/checker/model
    check_vcs --> github.com/murex/tcr/params
    check_vcs --> github.com/murex/tcr/vcs/git
    check_vcs --> github.com/murex/tcr/vcs/p4
    check_vcs --> strings
    check_vcs --> time
    check_vcs_test --> github.com/murex/tcr/checker/model
    check_vcs_test --> github.com/murex/tcr/params
    check_vcs_test --> github.com/murex/tcr/vcs/git
    check_vcs_test --> github.com/murex/tcr/vcs/p4
    check_vcs_test --> github.com/stretchr/testify/assert
    check_vcs_test --> testing
    check_vcs_test --> time
    check_workflow --> github.com/murex/tcr/checker/model
    check_workflow --> github.com/murex/tcr/params
    check_workflow_test --> github.com/murex/tcr/checker/model
    check_workflow_test --> github.com/murex/tcr/params
    check_workflow_test --> github.com/stretchr/testify/assert
    check_workflow_test --> testing
    check_group --> github.com/murex/tcr/report
    check_group_test --> github.com/murex/tcr/report
    check_group_test --> github.com/stretchr/testify/assert
    check_group_test --> testing
    check_point --> errors
    check_point --> fmt
    check_point --> github.com/murex/tcr/report
    check_point --> io/fs
    check_point_test --> errors
    check_point_test --> github.com/murex/tcr/report
    check_point_test --> github.com/stretchr/testify/assert
    check_point_test --> io/fs
    check_point_test --> testing
    check_status --> github.com/murex/tcr/status
    check_status_test --> github.com/murex/tcr/status
    check_status_test --> github.com/stretchr/testify/assert
    check_status_test --> testing
    runner --> github.com/murex/tcr/checker/model
    runner --> github.com/murex/tcr/config
    runner --> github.com/murex/tcr/filesystem
    runner --> github.com/murex/tcr/language
    runner --> github.com/murex/tcr/params
    runner --> github.com/murex/tcr/report
    runner --> github.com/murex/tcr/toolchain
    runner --> github.com/murex/tcr/vcs
    runner --> github.com/murex/tcr/vcs/factory
    runner_test --> github.com/murex/tcr/checker/model
    runner_test --> github.com/murex/tcr/params
    runner_test --> github.com/murex/tcr/status
    runner_test --> github.com/murex/tcr/vcs
    runner_test --> github.com/murex/tcr/vcs/factory
    runner_test --> github.com/murex/tcr/vcs/fake
    runner_test --> github.com/stretchr/testify/assert
    runner_test --> testing
    menu --> bytes
    menu --> errors
    menu --> fmt
    menu_test --> github.com/stretchr/testify/assert
    menu_test --> testing
    print --> fmt
    print --> github.com/logrusorgru/aurora
    print --> strings
    print_test --> github.com/stretchr/testify/assert
    print_test --> github.com/zenizh/go-capturer
    print_test --> strings
    print_test --> testing
    terminal --> bytes
    terminal --> github.com/codeskyblue/go-sh
    terminal --> github.com/murex/tcr/report
    terminal --> os
    terminal --> os/exec
    terminal --> os/signal
    terminal --> strconv
    terminal --> strings
    terminal_ui --> fmt
    terminal_ui --> github.com/murex/tcr/desktop
    terminal_ui --> github.com/murex/tcr/engine
    terminal_ui --> github.com/murex/tcr/params
    terminal_ui --> github.com/murex/tcr/report
    terminal_ui --> github.com/murex/tcr/report/role_event
    terminal_ui --> github.com/murex/tcr/report/text
    terminal_ui --> github.com/murex/tcr/report/timer_event
    terminal_ui --> github.com/murex/tcr/role
    terminal_ui --> github.com/murex/tcr/runmode
    terminal_ui --> github.com/murex/tcr/settings
    terminal_ui --> github.com/murex/tcr/timer
    terminal_ui --> github.com/murex/tcr/vcs/git
    terminal_ui --> github.com/murex/tcr/vcs/p4
    terminal_ui --> os
    terminal_ui_test --> github.com/murex/tcr/desktop
    terminal_ui_test --> github.com/murex/tcr/engine
    terminal_ui_test --> github.com/murex/tcr/params
    terminal_ui_test --> github.com/murex/tcr/report
    terminal_ui_test --> github.com/murex/tcr/report/role_event
    terminal_ui_test --> github.com/murex/tcr/report/timer_event
    terminal_ui_test --> github.com/murex/tcr/role
    terminal_ui_test --> github.com/murex/tcr/runmode
    terminal_ui_test --> github.com/murex/tcr/timer
    terminal_ui_test --> github.com/murex/tcr/vcs/git
    terminal_ui_test --> github.com/murex/tcr/vcs/p4
    terminal_ui_test --> github.com/stretchr/testify/assert
    terminal_ui_test --> github.com/zenizh/go-capturer
    terminal_ui_test --> os
    terminal_ui_test --> strings
    terminal_ui_test --> testing
    terminal_ui_test --> time
    terminal_windows --> golang.org/x/sys/windows
    terminal_windows --> os
    check --> github.com/murex/tcr/cli
    check --> github.com/murex/tcr/engine
    check --> github.com/murex/tcr/runmode
    check --> github.com/spf13/cobra
    config --> github.com/murex/tcr/config
    config --> github.com/spf13/cobra
    info --> github.com/murex/tcr/settings
    info --> github.com/spf13/cobra
    log --> github.com/murex/tcr/cli
    log --> github.com/murex/tcr/engine
    log --> github.com/murex/tcr/runmode
    log --> github.com/spf13/cobra
    mob --> github.com/murex/tcr/cli
    mob --> github.com/murex/tcr/engine
    mob --> github.com/murex/tcr/runmode
    mob --> github.com/spf13/cobra
    one_shot --> github.com/murex/tcr/cli
    one_shot --> github.com/murex/tcr/engine
    one_shot --> github.com/murex/tcr/runmode
    one_shot --> github.com/spf13/cobra
    root --> github.com/murex/tcr/cli
    root --> github.com/murex/tcr/config
    root --> github.com/murex/tcr/engine
    root --> github.com/murex/tcr/params
    root --> github.com/murex/tcr/runmode
    root --> github.com/murex/tcr/settings
    root --> github.com/spf13/cobra
    solo --> github.com/murex/tcr/cli
    solo --> github.com/murex/tcr/engine
    solo --> github.com/murex/tcr/runmode
    solo --> github.com/spf13/cobra
    stats --> github.com/murex/tcr/cli
    stats --> github.com/murex/tcr/engine
    stats --> github.com/murex/tcr/runmode
    stats --> github.com/spf13/cobra
    web --> github.com/murex/tcr/cli
    web --> github.com/murex/tcr/engine
    web --> github.com/murex/tcr/http
    web --> github.com/murex/tcr/runmode
    web --> github.com/spf13/cobra
    param_auto_push --> github.com/spf13/cobra
    param_base_dir --> github.com/spf13/cobra
    param_commit_failures --> github.com/spf13/cobra
    param_config_dir --> github.com/spf13/cobra
    param_language --> github.com/spf13/cobra
    param_message_suffix --> github.com/spf13/cobra
    param_mob_timer_duration --> github.com/spf13/cobra
    param_mob_timer_duration --> time
    param_polling_period --> github.com/spf13/cobra
    param_polling_period --> time
    param_port_number --> github.com/spf13/cobra
    param_toolchain --> github.com/spf13/cobra
    param_trace --> github.com/spf13/cobra
    param_vcs --> github.com/spf13/cobra
    param_work_dir --> github.com/spf13/cobra
    settings --> fmt
    settings --> github.com/spf13/cobra
    settings --> github.com/spf13/pflag
    settings --> github.com/spf13/viper
    tcr_config --> github.com/murex/tcr/language
    tcr_config --> github.com/murex/tcr/params
    tcr_config --> github.com/murex/tcr/settings
    tcr_config --> github.com/murex/tcr/toolchain
    tcr_config --> github.com/murex/tcr/utils
    tcr_config --> github.com/spf13/cobra
    tcr_config --> github.com/spf13/viper
    tcr_config --> io
    tcr_config --> os
    tcr_config --> path/filepath
    tcr_config --> sort
    tcr_config_test --> fmt
    tcr_config_test --> github.com/murex/tcr/language
    tcr_config_test --> github.com/murex/tcr/params
    tcr_config_test --> github.com/murex/tcr/toolchain
    tcr_config_test --> github.com/murex/tcr/utils
    tcr_config_test --> github.com/spf13/cobra
    tcr_config_test --> github.com/stretchr/testify/assert
    tcr_config_test --> os
    tcr_config_test --> path/filepath
    tcr_config_test --> testing
    tcr_config_test --> time
    type_bool --> github.com/spf13/cobra
    type_bool --> github.com/spf13/viper
    type_duration --> github.com/spf13/cobra
    type_duration --> github.com/spf13/viper
    type_duration --> time
    type_int --> github.com/spf13/cobra
    type_int --> github.com/spf13/viper
    type_string --> github.com/spf13/cobra
    type_string --> github.com/spf13/viper
    browser --> fmt
    browser --> github.com/murex/tcr/report
    browser --> github.com/pkg/browser
    browser --> net/url
    browser_test --> github.com/stretchr/testify/assert
    browser_test --> testing
    notification --> github.com/gen2brain/beeep
    notification_test --> github.com/pkg/errors
    notification_test --> github.com/stretchr/testify/assert
    notification_test --> testing
    living_doc_tour_guide --> bufio
    living_doc_tour_guide --> fmt
    living_doc_tour_guide --> os
    living_doc_tour_guide --> regexp
    living_doc_tour_guide --> sort
    living_doc_tour_guide --> strconv
    living_doc_tour_guide --> strings
    living_doc_tour_guide_test --> testing
    tcr --> errors
    tcr --> github.com/murex/tcr/checker
    tcr --> github.com/murex/tcr/events
    tcr --> github.com/murex/tcr/filesystem
    tcr --> github.com/murex/tcr/language
    tcr --> github.com/murex/tcr/params
    tcr --> github.com/murex/tcr/report
    tcr --> github.com/murex/tcr/report/role_event
    tcr --> github.com/murex/tcr/role
    tcr --> github.com/murex/tcr/runmode
    tcr --> github.com/murex/tcr/settings
    tcr --> github.com/murex/tcr/stats
    tcr --> github.com/murex/tcr/status
    tcr --> github.com/murex/tcr/timer
    tcr --> github.com/murex/tcr/toolchain
    tcr --> github.com/murex/tcr/ui
    tcr --> github.com/murex/tcr/vcs
    tcr --> github.com/murex/tcr/vcs/factory
    tcr --> gopkg.in/tomb.v2
    tcr --> os
    tcr --> strings
    tcr --> sync
    tcr --> time
    tcr_test --> fmt
    tcr_test --> github.com/murex/tcr/events
    tcr_test --> github.com/murex/tcr/language
    tcr_test --> github.com/murex/tcr/params
    tcr_test --> github.com/murex/tcr/report
    tcr_test --> github.com/murex/tcr/role
    tcr_test --> github.com/murex/tcr/runmode
    tcr_test --> github.com/murex/tcr/settings
    tcr_test --> github.com/murex/tcr/status
    tcr_test --> github.com/murex/tcr/toolchain
    tcr_test --> github.com/murex/tcr/ui
    tcr_test --> github.com/murex/tcr/vcs
    tcr_test --> github.com/murex/tcr/vcs/factory
    tcr_test --> github.com/murex/tcr/vcs/fake
    tcr_test --> github.com/stretchr/testify/assert
    tcr_test --> os
    tcr_test --> strings
    tcr_test --> testing
    tcr_test --> time
    tcr_test_fake --> github.com/murex/tcr/params
    tcr_test_fake --> github.com/murex/tcr/role
    tcr_test_fake --> github.com/murex/tcr/status
    tcr_test_fake --> github.com/murex/tcr/timer
    tcr_test_fake --> github.com/murex/tcr/ui
    aggregates --> time
    aggregates_test --> github.com/stretchr/testify/assert
    aggregates_test --> testing
    aggregates_test --> time
    dated_tcr_event --> time
    dated_tcr_event_test --> github.com/stretchr/testify/assert
    dated_tcr_event_test --> testing
    dated_tcr_event_test --> time
    dated_tcr_event_test_data_builder --> time
    tcr_event --> time
    tcr_event_test --> github.com/stretchr/testify/assert
    tcr_event_test --> testing
    tcr_event_test --> time
    tcr_event_test_data_builder --> time
    tcr_events --> sort
    tcr_events --> time
    tcr_events_test --> github.com/stretchr/testify/assert
    tcr_events_test --> sort
    tcr_events_test --> testing
    tcr_events_test --> time
    utils --> time
    value_and_ratio --> time
    value_and_ratio_test --> github.com/stretchr/testify/assert
    value_and_ratio_test --> testing
    value_and_ratio_test --> time
    value_evolution --> time
    value_evolution_test --> github.com/stretchr/testify/assert
    value_evolution_test --> testing
    value_evolution_test --> time
    yaml --> bytes
    yaml --> github.com/murex/tcr/report
    yaml --> gopkg.in/yaml.v3
    yaml --> time
    yaml_test --> github.com/stretchr/testify/assert
    yaml_test --> testing
    yaml_test --> time
    sourcetree_impl --> errors
    sourcetree_impl --> github.com/fsnotify/fsnotify
    sourcetree_impl --> github.com/murex/tcr/report
    sourcetree_impl --> os
    sourcetree_impl --> path/filepath
    sourcetree_impl_test --> github.com/murex/tcr/report
    sourcetree_impl_test --> github.com/stretchr/testify/assert
    sourcetree_impl_test --> os
    sourcetree_impl_test --> path/filepath
    sourcetree_impl_test --> testing
    sourcetree_impl_test --> time
    build_info --> github.com/gin-gonic/gin
    build_info --> github.com/murex/tcr/settings
    build_info --> net/http
    build_info_test --> encoding/json
    build_info_test --> github.com/gin-gonic/gin
    build_info_test --> github.com/murex/tcr/settings
    build_info_test --> github.com/stretchr/testify/assert
    build_info_test --> net/http
    build_info_test --> net/http/httptest
    build_info_test --> testing
    context --> github.com/gin-gonic/gin
    context --> github.com/murex/tcr/engine
    roles --> github.com/gin-gonic/gin
    roles --> github.com/murex/tcr/report
    roles --> github.com/murex/tcr/role
    roles --> net/http
    roles_test --> encoding/json
    roles_test --> github.com/gin-gonic/gin
    roles_test --> github.com/murex/tcr/engine
    roles_test --> github.com/murex/tcr/role
    roles_test --> github.com/stretchr/testify/assert
    roles_test --> net/http
    roles_test --> net/http/httptest
    roles_test --> strings
    roles_test --> testing
    session_info --> github.com/gin-gonic/gin
    session_info --> net/http
    session_info_test --> encoding/json
    session_info_test --> github.com/gin-gonic/gin
    session_info_test --> github.com/murex/tcr/engine
    session_info_test --> github.com/stretchr/testify/assert
    session_info_test --> net/http
    session_info_test --> net/http/httptest
    session_info_test --> testing
    timer --> fmt
    timer --> github.com/gin-gonic/gin
    timer --> net/http
    timer_test --> encoding/json
    timer_test --> github.com/gin-gonic/gin
    timer_test --> github.com/murex/tcr/engine
    timer_test --> github.com/stretchr/testify/assert
    timer_test --> net/http
    timer_test --> net/http/httptest
    timer_test --> testing
    static --> embed
    static --> github.com/gin-contrib/static
    static --> io/fs
    static --> net/http
    static_test --> embed
    static_test --> github.com/stretchr/testify/assert
    static_test --> testing
    web_ui_server --> context
    web_ui_server --> fmt
    web_ui_server --> github.com/gin-contrib/cors
    web_ui_server --> github.com/gin-contrib/static
    web_ui_server --> github.com/gin-gonic/gin
    web_ui_server --> github.com/murex/tcr/engine
    web_ui_server --> github.com/murex/tcr/http/api
    web_ui_server --> github.com/murex/tcr/http/ws
    web_ui_server --> github.com/murex/tcr/params
    web_ui_server --> github.com/murex/tcr/report
    web_ui_server --> github.com/murex/tcr/runmode
    web_ui_server --> net/http
    web_ui_server --> time
    web_ui_server_test --> github.com/gin-gonic/gin
    web_ui_server_test --> github.com/murex/tcr/engine
    web_ui_server_test --> github.com/murex/tcr/params
    web_ui_server_test --> github.com/stretchr/testify/assert
    web_ui_server_test --> net/http
    web_ui_server_test --> net/http/httptest
    web_ui_server_test --> slices
    web_ui_server_test --> strings
    web_ui_server_test --> testing
    web_ui_server_test --> time
    context --> context
    context --> github.com/gin-gonic/gin
    context --> net/http
    context --> time
    context_test --> github.com/gin-gonic/gin
    context_test --> github.com/stretchr/testify/assert
    context_test --> net/http
    context_test --> testing
    websocket --> fmt
    websocket --> github.com/gin-gonic/gin
    websocket --> github.com/gorilla/websocket
    websocket --> github.com/murex/tcr/report
    websocket --> github.com/murex/tcr/report/role_event
    websocket --> github.com/murex/tcr/report/text
    websocket --> github.com/murex/tcr/report/timer_event
    websocket --> net/http
    websocket --> net/url
    websocket --> strconv
    websocket --> sync
    websocket --> time
